name: Qatar Living Auto Refresh

on:
  schedule:
    # Run at 9 AM, 12 PM, 3 PM, 6 PM Qatar time (6 AM, 9 AM, 12 PM, 3 PM UTC)
    - cron: '0 6,9,12,15 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  refresh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Qatar Living Auto Refresh
      env:
        QATAR_COOKIES: ${{ secrets.QATAR_COOKIES }}
      run: |
        python refresh_post.py
